# -*- coding: utf-8 -*-
"""training_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aMSVVSAs6En4GqDDPtmARvR0Gnrxma0V
"""

import pandas as pd
from sklearn.model_selection import train_test_split

patients = pd.read_csv("problemas_del_corazon.csv")

#dsplit data into "rest of data", "data for test", "objective class" & "test class "
data, test_data, myClass, test_class = train_test_split(
                  patients[["edad","genero", "presion", "colesterol", "diabetico"]],
                  patients["cardiaco"],
                  test_size=0.20)

#split into "training data", "validation", "rest of class", "test class"
training_data, validation_data, training_class, validation_class = train_test_split(
                  data[["edad","genero", "presion", "colesterol", "diabetico"]],
                  myClass,
                  test_size= 0.25 #in this case applies 0.25 because we are testing with 20% of data, and data after first training split has 80 rows instead 100
                  )


#first cut of data (to set 80% of data, 20% of training, 0% of validation [is mishing, thats why we split it again])
# print(f"\n\n Data: \n {data}")
# print(f"\n\n Test: \n {test_data}")
# print(f"\n\n Class: \n {myClass}")
# print(f"\n\n Test Class: \n {test_class}")

#second cut (to set correctly 60% of data, 20% of training, 20% of validation)
print(f"\n\n Data: \n {training_data}")
print(f"\n\n Test: \n {validation_data}")
print(f"\n\n Class: \n {training_class}")
print(f"\n\n Test Class: \n {validation_class}")