# -*- coding: utf-8 -*-
"""covariance_array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XnRiBaT5sUqnAITaujiJJtKdNPSLKEZt
"""

#variance and standardesviation with panadas
import pandas as pd
import matplotlib.pyplot as plt
 #take scientific totation away
pd.options.display.float_format = '{:.2f}'.format

 #context
 # (0) Age,
 # (1) monthly bills in medicine,
 # (2) monthly bills in education,
 # (3) monthly bills in maní,


data = {
     "age":[35, 50, 22, 45, 18, 75, 55,  20, 23, 49],
     "medicine":[200, 1500, 150, 250, 0, 2500, 1400, 50, 0, 600],
     "education":[1200, 0, 7500, 2200, 8300, 0, 0, 4900, 5100, 800],
     "cacahuates":[10, 15, 0, 10, 20, 10, 20, 10, 15, 0]
 }

data = pd.DataFrame(data)
data


data.aggregate(["std", "var"])

#graphication
def subgraphic_std(data, col, fig, pos):
  ax = fig.add_subplot(1, 4, pos)

  #calculatemedia and standard deviation
  media = data[col].mean()
  std = data[col].std()

  #graphic of data
  ax.scatter(range(len(data[col])), data[col], marker="D", s=150, color="purple")

  #graphic of media and standard deviation
  ax.axhline(y=media+std, color="gray", linestyle="--", linewidth = 3)
  ax.axhline(y=media, color="teal", linestyle="--", linewidth = 6)
  ax.axhline(y=media-std, color="gray", linestyle="--", linewidth = 3)

  #presenttion of graphic
  ax.set_title("dev std:" + col.capitalize(), fontsize=20)
  ax.set_xticks(range(len(data[col])))
  ax.get_xaxis().set_visible(False)

#standar deviation to every column
fig = plt.figure(figsize=(18, 5))

subgraphic_std(data, "age", fig, 1)
subgraphic_std(data, "medicine", fig, 2)
subgraphic_std(data, "education", fig, 3)
subgraphic_std(data, "cacahuates", fig, 4)

print(data.var())
data.cov()

def subgraphic_dispersion(data, col_a, col_b, fig, pos, text):
  ax = fig.add_subplot(1,3, pos)
  ax.scatter(data[col_a], data[col_b], marker="8", s=250, color="purple")
  ax.set_xlabel(col_a.capitalize(), fontsize=20, color="darkblue")
  ax.set_ylabel(col_b.capitalize(), fontsize=20, color="darkblue")
  ax.text(54, 0, text, fontsize=28, color="red")

#print of covariance array
print(data[["age", "medicine"]].cov(), "\n")
print(data[["age",  "education"]].cov(), "\n")
print(data[["age", "cacahuates"]].cov(), "\n")

#graphics
fig = plt.figure(figsize=(20,6))
subgraphic_dispersion(data, "age", "medicine", fig, 1, "Positiva")
subgraphic_dispersion(data, "age", "education", fig, 2, "Negative")
subgraphic_dispersion(data, "age", "cacahuates", fig, 3, "~ Cero")

#print of covariance array
print(data[["medicine", "education"]].cov(), "\n")
print(data[["medicine",  "cacahuates"]].cov(), "\n")
print(data[["education", "cacahuates"]].cov(), "\n")

#graphics
fig = plt.figure(figsize=(20,6))
subgraphic_dispersion(data, "medicine", "education", fig, 1, "Positiva")
subgraphic_dispersion(data, "medicine", "cacahuates", fig, 2, "Negative")
subgraphic_dispersion(data, "education", "cacahuates", fig, 3, "~ Cero")

plt.show()