# -*- coding: utf-8 -*-
"""discretazing_numeric_datas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kDrihmHeEF5da0ekAUylw2w_VUv2RNze
"""

import numpy as np
import pandas as pd

ages = np.array([1,7,8,15,16,28,35,50,55,70,75,100])

result = pd.cut(ages,
                bins=3,
                labels=["low", "media", "high"],
                include_lowest=True,
                retbins=True)

print(result[1], "\n")
print(result[0].codes, "\n")
print(result[0].categories, "\n")
print(np.array(result[0]), "\n")

#cathegorize for ages with diferent sizes

ages = np.array([1,7,8,15,16,28,35,50,55,70,75,100])

result = pd.cut(ages,
                bins=[0, 11, 17, 59, np.inf],  #------------------adding ranges
                labels=["child", "young", "adult", "old"],
                include_lowest=True,
                retbins=True)

print(result[1], "\n")
print(result[0].codes, "\n")
print(result[0].categories, "\n")
print(np.array(result[0]), "\n")