# -*- coding: utf-8 -*-
"""isolation_forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_kPlrBFT9yQJ3T-hQJQ_0qqLESzAwy-0
"""

import numpy as np
import matplotlib as plt
from sklearn.ensemble import IsolationForest

#loaddata
cars = np.loadtxt("carros_usados.csv", delimiter=",")
results = np.zeros((3, cars.size//2))

#isolation forest with diferent pollution
c =[0.00, 0.05, 0.1]

for i in range(len(c)):
  mymodel = IsolationForest(contamination = c[i]).fit(cars)
  results[i] = mymodel.predict(cars)

#ggrapic anormal data
plt.set_cmap("jet")
fig = plt.figure(figsize=(13,4))

for i in range(len(c)):
  ax = fig.add_subplot(1,3, i+1)
  ax.scatter(cars[results[i]==-1][:,0],
             cars[results[i]==1][:,1],
             c="skyblue", marker="s", s=500)
  ax.scatter(cars[:,0],
             cars[:,1],
             c=range(cars.size//2), marker="x",
             s=500, alpha=0.6)

  ax.set_title("Contamination: %0.2f" % c[i], size=18, color="purple")
  ax.set_ylabel("Price ($)", size = 10)
  ax.set_xlabel("kms traveled", size = 14)

plt.show()

