# -*- coding: utf-8 -*-
"""Linear_regresion_python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JX-tWuMwfbbNXaGPNLEmogUFvIb8qooS
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

data = pd.read_csv("ingreso.csv")
# data
#graphic of dispersion
plt.ylabel("Earnings ($)")
plt.xlabel("Average of weekly working hours")
plt.scatter(data["horas"], data["ingreso"], color="pink")
plt.show()

regresion = linear_model.LinearRegression()
hours = data["horas"].values.reshape((-1,1))

myModel = regresion.fit(hours, data["ingreso"])

print("Intersection (b): ", myModel.intercept_)
print("Slope  (b): ", myModel.coef_)

inputVector = [[39],[40],[43],[44]]

myModel.predict(inputVector)

plt.scatter(inputVector, myModel.predict(inputVector), color="red")
plt.plot(inputVector, myModel.predict(inputVector), color="black")
plt.ylabel("Earnings ($)")
plt.xlabel("Average of weekly working hours")
plt.scatter(data["horas"], data["ingreso"], color="pink")
plt.show()

"""# Sección nueva"""