# -*- coding: utf-8 -*-
"""cluster_optimizarion_with_bdscan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13V5gVzc3GlDa2-U-2-WoP1nuFfoeCF0D
"""

#dbscanm density based spatial clustering od Applicaitions with noise
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN

#load data
myData = np.loadtxt("casas.csv", delimiter=",")

#identify clusters
clusters = DBSCAN(eps=2, min_samples=10).fit_predict(myData)
print(clusters)

#matplotlib graphic to show clusters
plt.figure(figsize=(7.5,7.5))
plt.scatter(myData[:,0], myData[:,1], c=clusters, s=100)
plt.xlabel("Building's age in years")
plt.ylabel("Home prices in mexican pesos (1:100,000)")
plt.box(False)
plt.show()