# -*- coding: utf-8 -*-
"""imputation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QU1yw2HzxPKXXN_3MiDh1VVY0mb-8-mq
"""

import pandas as pd
myData = pd.read_csv("clients.csv")
#all value
#print(myData["nombre"])
#onlyData null
#print(myData[myData["nombre"].isnull()])

# delete data null
#print(myData.dropna())


# print(myData.dropna(subset=["nombre","ingreso"]))

#replace na
#print(myData.fillna(0))

#edit name
# print(myData["nombre"].fillna("Desconocido"))

def edit_multiple_cols():
  #edit multiple cols
  defect_values = {
      "nombre": "Desconocido",
      "edad": 18,
      "ingreso": 10000
  }

  print(myData.fillna(value=defect_values))

def edit_multiple_cols_with_special_data():

  #edit multiple cols with specific values
  #those measires are used to replace null data inside dataframes
  #to set it with more logic and quantity for models

  average  = myData["ingreso"].mean()
  mymedian = myData["ingreso"].median()
  moda = myData["ingreso"].mode()[0]

  defect_values = {
      "nombre": "Desconocido",
      "edad": 18,
      "ingreso": mymedian
  }
  print(average,mymedian,moda)
  print(myData.fillna(value=defect_values))

edit_multiple_cols_with_special_data()